# Домашнее задание «Библиотека Pandas»

## Задание 1

In [181]:
import pandas as pd
ratings=pd.read_csv('ratings.csv')
movies=pd.read_csv('movies.csv')
joined = ratings.merge(movies, on='movieId', how='left')
joined= joined.sort_values('rating').head(30)
joined.head(30)
title = joined.title.head(1)
best= title.tolist()
print('Больше всего оценок 5.0 выставлено фильму:',best[0])

Больше всего оценок 5.0 выставлено фильму: Death Proof (2007)

## Задание 2

In [180]:
import pandas as pd
data = pd.read_csv('power.csv')
filter_countries=data[(data['country']=='Latvia') | (data['country']=='Lithuania') | (data['country']=='Estonia')]
filter_countries_year=filter_countries.sort_values('year')
filter_countries_years=filter_countries_year[filter_countries_year['year'].isin(['2005', '2006', '2007', '2008', '2009', '2010'])]
def category(numb):
    filter_category = filter_countries_years[filter_countries_years['category'].isin([(numb)])]
    res=0
    for i in filter_category.quantity:
        if i > 0:
            res+=i
    print('Для категории',numb,'потребление стран -',int(res))
category(4) 
category(12) 
category(21)

Для категории 4 потребление стран - 46
Для категории 12 потребление стран - 6326
Для категории 21 потребление стран - 234208

## Задание 3

In [179]:
import pandas as pd
table=pd.read_html('https://www.profinance.ru/currency_usd.asp',attrs={'id':'curtable'})
table[0].drop([4,5],axis=1)

      0          1                        2          3
0   Код  За единиц                   Валюты  Рублей РФ
1   AUD          1     Австралийский доллар    55.4793
2   AZN          1    Азербайджанский манат    42.3969
3   AMD        100         Армянских драмов    13.9684
4   BYN          1        Белорусский рубль    28.8683
5   BGN          1           Болгарский лев    44.6601
6   BRL          1         Бразильский реал    14.2771
7   HUF        100      Венгерских форинтов    24.8812
8   KRW       1000     Вон Республики Корея      64.44
9   HKD         10     Гонконгских долларов    92.8024
10  DKK          1            Датская крона    11.7458
11  USD          1               Доллар США    72.0323
12  EUR          1                     Евро    87.3536
13  INR        100          Индийских рупий    98.1848
14  KZT        100      Казахстанских тенге    16.9052
15  CAD          1         Канадский доллар    59.1156
16  KGS        100         Киргизских сомов    85.1646
17  CNY          1           Китайский юань    11.2589
18  MDL         10          Молдавских леев    40.5679
19  TMT          1  Новый туркменский манат    20.6101
20  NOK         10          Норвежских крон    86.4059
21  PLN          1          Польский злотый    19.2847
22  RON          1            Румынский лей    17.7376
23  XDR          1                      СДР   103.6667
24  SGD          1      Сингапурский доллар    54.3148
25  TJS         10        Таджикских сомони    63.1585
26  TRY         10             Турецких лир    84.4805
27  UZS      10000          Узбекских сумов    67.8525
28  UAH         10        Украинских гривен    26.6764
29  GBP          1          Фунт стерлингов   101.6304
30  CZK         10             Чешских крон    34.2848
31  SEK         10            Шведских крон    86.3562
32  CHF          1        Швейцарский франк    80.1874
33  ZAR         10   Южноафриканских рэндов     52.327
34  JPY        100             Японских иен    65.5286